from config import (
    CHECKPOINT_DIR,
    CLASS_OFFSET,
    DATA_DIR,
    DEVICE,
    LEARNING_RATE,
    LR_FACTOR,
    LR_MIN,
    LR_PATIENCE,
    MOMENTUM,
    NUM_CLASSES,
    PIN_MEMORY,
    PRETRAINED,
    SEED,
    TRAINABLE_BACKBONE_LAYERS,
    WEIGHT_DECAY,
)

BATCH_SIZE = 1
NUM_WORKERS = 0
NUM_EPOCHS = 2

SMOKE_TRAIN_SAMPLES = 64
SMOKE_VALID_SAMPLES = 16

SMOKE_CHECKPOINT_DIR = CHECKPOINT_DIR / "smoke"
SMOKE_LAST_MODEL_PATH = SMOKE_CHECKPOINT_DIR / "last_model.pth"
SMOKE_BEST_MODEL_PATH = SMOKE_CHECKPOINT_DIR / "best_model.pth"
